"""Tests for WAV LSB embedding and extraction.

Deliberately mirrors ``tests/test_image_stego.py``: the same properties, the same
boundary cases, the same error categories.

The last class, ``TestCrossMediaParity``, is the one that keeps the two halves
honest: it asserts that both layers produce the same bit ordering, the same encoded
stream layout and the same error types for identical inputs.
"""

from __future__ import annotations

import math
import os
from pathlib import Path

import numpy as np
import pytest
import soundfile as sf
from hypothesis import given, settings
from hypothesis import strategies as st

from app.stego import audio_stego, bit_utils, capacity, image_io, image_stego
from app.stego.errors import (
    CapacityError,
    DecodeError,
    ExtractionError,
    FileError,
    StegoError,
    ValidationError,
)

from conftest import (
    AUDIO_SAMPLE_RATE,
    ScratchDirectory,
    make_audio,
    make_cover,
    write_audio_file,
    write_cover,
)

PAYLOAD = b"INF2005 Audio LSB Test"


# --------------------------------------------------------------------------- #
# Evidence
# --------------------------------------------------------------------------- #
#
# The round-trip table in evidence/results/ is generated from the run that proves it,
# so the committed artefact cannot drift from the code.

_ROUND_TRIP: list[dict[str, object]] = []


@pytest.fixture(scope="module", autouse=True)
def write_round_trip_evidence(evidence_directory):
    _ROUND_TRIP.clear()
    yield

    if evidence_directory is None or not _ROUND_TRIP:
        return

    from app.utils import file_utils

    directory = evidence_directory
    rows = sorted(_ROUND_TRIP, key=lambda row: row["lsb_depth"])

    file_utils.write_json_atomic(
        str(directory / "audio_lsb_round_trip.json"),
        {
            "experiment": "audio LSB round trip at every selectable depth",
            "cover_format": "WAV PCM_16",
            "encoded_stream": "4-byte big-endian payload length, then the payload",
            "cases": rows,
            "passed": sum(1 for row in rows if row["passed"]),
            "total": len(rows),
        },
        overwrite=True,
    )

    lines = [
        "# Audio LSB Round-Trip Results",
        "",
        "Generated by `tests/test_audio_stego.py`. Do not edit by hand: an earlier "
        "hand-written version of this file went stale and described a payload format "
        "the code no longer uses.",
        "",
        "## What is being established",
        "",
        "That a payload embedded in a 16-bit PCM WAV cover extracts back byte-for-byte "
        "at every selectable LSB depth from 1 to 8, from a non-zero start location.",
        "",
        "## The encoded stream",
        "",
        "The audio layer writes a **bare 4-byte big-endian payload length followed by "
        "the payload bytes**, and nothing else. It is identical to the image layer's "
        "stream.",
        "",
        "There is no magic marker at this level. An earlier version of this layer wrote "
        "a `b\"INF2005\"` marker into the medium while the image layer wrote none; the "
        "marker now lives in the shared payload envelope "
        "(`app/crypto/envelope.py`, magic `INF2005E`), so both media get the same "
        "\"is there a payload here?\" signal and the stego layer stays free of any "
        "knowledge of what the bytes mean.",
        "",
        "Bits are written most-significant-bit first into the chosen number of "
        "lowest-order bits of consecutive scalar samples, in interleaved channel order, "
        "never wrapping. There is no realignment after the 32-bit header, so at depths "
        "that do not divide 32 the first payload bit sits partway through a sample. "
        "Depths 3, 5, 6 and 7 exercise that case.",
        "",
        "## Start location",
        "",
        "This layer takes a caller-supplied integer index and holds no key material. "
        "Deriving an index from a secret is a cryptographic operation and lives in "
        "`app/crypto/start_location.py`; the `passcode` parameter this layer once "
        "accepted was removed for that reason.",
        "",
        "## Results",
        "",
        "| LSB depth | Cover frames | Start | Payload bytes | Samples written | "
        "Max sample change | Bound | Recovered | Result |",
        "|---:|---:|---:|---:|---:|---:|---:|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['lsb_depth']} | {row['cover_frames']:,} | "
            f"{row['start_location']} | {row['payload_length']} | "
            f"{row['samples_written']} | {row['max_sample_change']} | "
            f"{row['distortion_bound']} | "
            f"{'exact' if row['payload_recovered'] else 'MISMATCH'} | "
            f"{'PASS' if row['passed'] else 'FAIL'} |"
        )

    lines += [
        "",
        f"{sum(1 for row in rows if row['passed'])} of {len(rows)} depths passed.",
        "",
        "## What else each row checks",
        "",
        "- **Max sample change against the bound.** Replacing the low *n* bits can move "
        "a sample by at most `2**n - 1`. A larger observed change would mean more was "
        "written than the depth accounts for.",
        "- **Bits above the depth unchanged.** Asserted separately by "
        "`TestCoverPreservation`, over generated covers rather than one fixed file.",
        "- **The cover file untouched on disk.** The layer refuses to write over its own "
        "input and writes atomically.",
        "",
        "## What this does not establish",
        "",
        "A successful round trip says nothing about authenticity. These bytes are opaque "
        "and unauthenticated at this layer: a wrong depth or start location can decode a "
        "plausible length and return wrong bytes with no error at all. The envelope "
        "magic and the signature above this layer are what establish that a payload is "
        "real. See `docs/limitations.md` §2.",
        "",
    ]
    file_utils.write_text_atomic(
        str(directory / "audio_lsb_round_trip.md"), "\n".join(lines), overwrite=True
    )


# --------------------------------------------------------------------------- #
# Strategies
# --------------------------------------------------------------------------- #
#
# Values are derived from earlier draws rather than filtered, exactly as
# conftest.embedding_case does for images, so Hypothesis never rejects an example.


@st.composite
def audio_case(draw):
    channels = draw(st.sampled_from((1, 2)))
    lsb_count = draw(st.integers(min_value=1, max_value=8))
    pattern = draw(st.sampled_from(("tone", "noise", "silence", "extremes", "ramp")))
    seed = draw(st.integers(min_value=0, max_value=2**32 - 1))

    header_samples = math.ceil(capacity.LENGTH_HEADER_BYTES * 8 / lsb_count)
    lowest_frames = max(1, math.ceil(header_samples / channels))
    frame_count = draw(st.integers(min_value=lowest_frames, max_value=2_048))

    total_samples = frame_count * channels
    room = (total_samples * lsb_count) // 8
    payload_ceiling = max(0, room - capacity.LENGTH_HEADER_BYTES)
    payload_length = draw(st.integers(min_value=0, max_value=min(256, payload_ceiling)))
    payload = draw(st.binary(min_size=payload_length, max_size=payload_length))

    needed = math.ceil(
        (payload_length + capacity.LENGTH_HEADER_BYTES) * 8 / lsb_count
    )
    highest_start = max(0, total_samples - needed)
    start_location = draw(st.integers(min_value=0, max_value=highest_start))

    return {
        "channels": channels,
        "lsb_count": lsb_count,
        "pattern": pattern,
        "seed": seed,
        "frame_count": frame_count,
        "payload": payload,
        "start_location": start_location,
    }


def write_case(directory: str, case: dict, name: str = "cover") -> str:
    samples = make_audio(
        case["frame_count"], case["channels"], case["pattern"], case["seed"]
    )
    return write_audio_file(directory, samples, name)


# --------------------------------------------------------------------------- #
# Round trip
# --------------------------------------------------------------------------- #


class TestRoundTrip:
    @pytest.mark.parametrize("lsb_count", range(1, 9))
    def test_every_depth_round_trips(self, tmp_path, lsb_count):
        """Also the case the committed round-trip evidence is generated from."""
        frames = 44_100
        cover = write_audio_file(str(tmp_path), make_audio(frames))
        stego = str(tmp_path / f"stego_{lsb_count}.wav")

        result = audio_stego.embed_audio(cover, stego, PAYLOAD, lsb_count, 100)
        recovered = audio_stego.extract_audio(stego, lsb_count, 100)

        original_samples, _ = audio_stego.read_audio(cover)
        stego_samples, _ = audio_stego.read_audio(stego)
        largest = int(
            np.abs(
                stego_samples.astype(np.int32) - original_samples.astype(np.int32)
            ).max(initial=0)
        )
        bound = (1 << lsb_count) - 1

        _ROUND_TRIP.append(
            {
                "lsb_depth": lsb_count,
                "cover_frames": frames,
                "start_location": 100,
                "payload_length": len(PAYLOAD),
                "samples_written": result.samples_written,
                "max_sample_change": largest,
                "distortion_bound": bound,
                "payload_recovered": recovered == PAYLOAD,
                "passed": recovered == PAYLOAD and largest <= bound,
            }
        )

        assert recovered == PAYLOAD
        assert largest <= bound
        # The cover must be left alone on disk, not merely in memory.
        assert Path(cover).exists()

    @given(audio_case())
    @settings(max_examples=40)
    def test_extract_returns_the_embedded_payload(self, case):
        with ScratchDirectory() as directory:
            cover = write_case(directory, case)
            stego = os.path.join(directory, "stego.wav")

            audio_stego.embed_audio(
                cover,
                stego,
                case["payload"],
                case["lsb_count"],
                case["start_location"],
            )
            recovered = audio_stego.extract_audio(
                stego, case["lsb_count"], case["start_location"]
            )
            assert recovered == case["payload"]

    def test_stereo_round_trips(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(8_000, channels=2))
        stego = str(tmp_path / "stego.wav")

        audio_stego.embed_audio(cover, stego, PAYLOAD, 2, 7)
        assert audio_stego.extract_audio(stego, 2, 7) == PAYLOAD

    def test_empty_payload_round_trips(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        stego = str(tmp_path / "stego.wav")

        audio_stego.embed_audio(cover, stego, b"", 1, 0)
        assert audio_stego.extract_audio(stego, 1, 0) == b""

    def test_bytearray_payload_is_accepted(self, tmp_path):
        """The old implementation rejected bytearray while the image layer took it."""
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        stego = str(tmp_path / "stego.wav")

        audio_stego.embed_audio(cover, stego, bytearray(PAYLOAD), 2, 0)
        assert audio_stego.extract_audio(stego, 2, 0) == PAYLOAD

    def test_numpy_integers_are_accepted(self, tmp_path):
        """Parity with the image layer, which accepts numpy integers."""
        cover = write_audio_file(str(tmp_path), make_audio(2_000))
        stego = str(tmp_path / "stego.wav")

        audio_stego.embed_audio(cover, stego, PAYLOAD, np.int64(3), np.int64(64))
        assert audio_stego.extract_audio(stego, np.int64(3), np.int64(64)) == PAYLOAD

    def test_payload_at_the_exact_capacity_round_trips(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(500))
        report, _ = audio_stego.measure_capacity(cover, 1, 0)
        payload = bytes(report.max_payload_length)
        stego = str(tmp_path / "stego.wav")

        audio_stego.embed_audio(cover, stego, payload, 1, 0)
        assert audio_stego.extract_audio(stego, 1, 0) == payload

    @pytest.mark.parametrize("depth", [3, 5, 6, 7])
    def test_depths_that_do_not_divide_the_header_round_trip(self, tmp_path, depth):
        """A realignment bug would corrupt every payload byte at these depths."""
        cover = write_audio_file(str(tmp_path), make_audio(4_000))
        stego = str(tmp_path / "stego.wav")

        audio_stego.embed_audio(cover, stego, PAYLOAD, depth, 13)
        assert audio_stego.extract_audio(stego, depth, 13) == PAYLOAD

    def test_extreme_samples_round_trip(self, tmp_path):
        """-32768 and 32767 exercise the int16 sign boundary."""
        cover = write_audio_file(
            str(tmp_path), make_audio(4_000, pattern="extremes", seed=5)
        )
        stego = str(tmp_path / "stego.wav")

        audio_stego.embed_audio(cover, stego, PAYLOAD, 8, 0)
        assert audio_stego.extract_audio(stego, 8, 0) == PAYLOAD


class TestSignedSampleHandling:
    """The int16/uint16 reinterpretation is the one real difference from images."""

    def test_negative_samples_are_reinterpreted_not_converted(self, tmp_path):
        samples = np.full(4_000, -1, dtype=np.int16)
        cover = write_audio_file(str(tmp_path), samples)
        stego = str(tmp_path / "stego.wav")

        result = audio_stego.embed_audio(cover, stego, b"\x00", 3, 0)
        written, _ = audio_stego.read_audio(stego)

        # Every cover sample is -1, which is 0xFFFF. Replacing the three low bits
        # can only produce 0xFFF8 to 0xFFFF, which as int16 is -8 to -1. A signed
        # arithmetic implementation, or a cast instead of a reinterpretation, would
        # produce values outside that range.
        touched = written[: result.samples_written]
        assert touched.min() >= -8
        assert touched.max() <= -1
        # 0xFFF8 (-8) must actually occur: the payload is almost all zero bits.
        assert -8 in set(np.unique(touched).tolist())
        # And the rest of the file is untouched.
        assert np.all(written[result.samples_written :] == -1)

    def test_the_stream_view_is_unsigned(self, tmp_path):
        samples = np.array([-1, -32768, 0, 32767], dtype=np.int16)
        flat, channels = audio_stego.embeddable_stream(samples)

        assert flat.dtype == np.uint16
        assert channels == 1
        assert flat.tolist() == [0xFFFF, 0x8000, 0x0000, 0x7FFF]

    def test_the_most_negative_sample_survives_a_round_trip(self, tmp_path):
        cover = write_audio_file(
            str(tmp_path), np.full(4_000, -32768, dtype=np.int16)
        )
        stego = str(tmp_path / "stego.wav")

        audio_stego.embed_audio(cover, stego, PAYLOAD, 1, 0)
        assert audio_stego.extract_audio(stego, 1, 0) == PAYLOAD

    def test_interleaved_channel_order_is_preserved(self):
        samples = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.int16)
        flat, channels = audio_stego.embeddable_stream(samples)
        assert channels == 2
        assert flat.view(np.int16).tolist() == [1, 2, 3, 4, 5, 6]


# --------------------------------------------------------------------------- #
# Cover preservation
# --------------------------------------------------------------------------- #


class TestCoverPreservation:
    @given(audio_case())
    @settings(max_examples=30)
    def test_bits_above_the_depth_are_unchanged(self, case):
        with ScratchDirectory() as directory:
            cover_path = write_case(directory, case)
            stego_path = os.path.join(directory, "stego.wav")
            audio_stego.embed_audio(
                cover_path,
                stego_path,
                case["payload"],
                case["lsb_count"],
                case["start_location"],
            )

            before, _ = audio_stego.read_audio(cover_path)
            after, _ = audio_stego.read_audio(stego_path)
            keep = np.uint16(0xFFFF ^ ((1 << case["lsb_count"]) - 1))

            assert np.array_equal(
                before.reshape(-1).view(np.uint16) & keep,
                after.reshape(-1).view(np.uint16) & keep,
            )

    @given(audio_case())
    @settings(max_examples=30)
    def test_samples_outside_the_written_range_are_identical(self, case):
        with ScratchDirectory() as directory:
            cover_path = write_case(directory, case)
            stego_path = os.path.join(directory, "stego.wav")
            result = audio_stego.embed_audio(
                cover_path,
                stego_path,
                case["payload"],
                case["lsb_count"],
                case["start_location"],
            )

            before, _ = audio_stego.read_audio(cover_path)
            after, _ = audio_stego.read_audio(stego_path)
            flat_before = before.reshape(-1)
            flat_after = after.reshape(-1)
            start = result.start_location
            end = start + result.samples_written

            assert np.array_equal(flat_before[:start], flat_after[:start])
            assert np.array_equal(flat_before[end:], flat_after[end:])

    @given(audio_case())
    @settings(max_examples=30)
    def test_per_sample_change_is_bounded_by_the_depth(self, case):
        with ScratchDirectory() as directory:
            cover_path = write_case(directory, case)
            stego_path = os.path.join(directory, "stego.wav")
            audio_stego.embed_audio(
                cover_path,
                stego_path,
                case["payload"],
                case["lsb_count"],
                case["start_location"],
            )

            before, _ = audio_stego.read_audio(cover_path)
            after, _ = audio_stego.read_audio(stego_path)
            difference = np.abs(
                before.astype(np.int64) - after.astype(np.int64)
            )
            assert difference.max(initial=0) < (1 << case["lsb_count"])

    def test_the_cover_file_is_left_byte_for_byte_unchanged(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(4_000))
        before = Path(cover).read_bytes()

        audio_stego.embed_audio(cover, str(tmp_path / "stego.wav"), PAYLOAD, 4, 0)
        assert Path(cover).read_bytes() == before

    def test_media_properties_are_preserved(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(4_000, channels=2))
        stego = str(tmp_path / "stego.wav")
        audio_stego.embed_audio(cover, stego, PAYLOAD, 4, 0)

        original = audio_stego.describe_only(cover)
        written = audio_stego.describe_only(stego)

        assert written.sample_rate == original.sample_rate
        assert written.channel_count == original.channel_count
        assert written.frame_count == original.frame_count
        assert written.subtype == original.subtype

    def test_wav_output_preserves_the_file_size(self, tmp_path):
        """PCM replaces sample bytes in place, so the size should not move."""
        cover = write_audio_file(str(tmp_path), make_audio(4_000))
        stego = str(tmp_path / "stego.wav")
        audio_stego.embed_audio(cover, stego, PAYLOAD, 4, 0)

        assert os.path.getsize(stego) == os.path.getsize(cover)


class TestDeterminism:
    def test_repeated_embedding_produces_identical_samples(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(4_000))
        first = str(tmp_path / "first.wav")
        second = str(tmp_path / "second.wav")

        audio_stego.embed_audio(cover, first, PAYLOAD, 3, 11)
        audio_stego.embed_audio(cover, second, PAYLOAD, 3, 11)

        assert Path(first).read_bytes() == Path(second).read_bytes()


# --------------------------------------------------------------------------- #
# Capacity
# --------------------------------------------------------------------------- #


class TestCapacity:
    def test_capacity_counts_every_channel(self, tmp_path):
        """Unlike an image's alpha channel, no audio channel is excluded."""
        mono = write_audio_file(str(tmp_path), make_audio(1_000), "mono")
        stereo = write_audio_file(
            str(tmp_path), make_audio(1_000, channels=2), "stereo"
        )

        mono_report, _ = audio_stego.measure_capacity(mono, 1)
        stereo_report, _ = audio_stego.measure_capacity(stereo, 1)

        assert stereo_report.total_embeddable_samples == (
            2 * mono_report.total_embeddable_samples
        )

    def test_capacity_grows_with_depth(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        capacities = [
            audio_stego.measure_capacity(cover, depth)[0].available_capacity_bytes
            for depth in range(1, 9)
        ]
        assert capacities == sorted(capacities)

    def test_measuring_does_not_raise_for_an_oversized_payload(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(100))
        report, _ = audio_stego.measure_capacity(cover, 1, 0, payload_length=10**6)
        assert report.payload_fits is False

    def test_descriptor_reports_the_media_properties(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(4_410, channels=2))
        _, descriptor = audio_stego.measure_capacity(cover, 1)

        assert descriptor.sample_rate == AUDIO_SAMPLE_RATE
        assert descriptor.channel_count == 2
        assert descriptor.frame_count == 4_410
        assert descriptor.total_samples == 8_820
        assert descriptor.duration_seconds == pytest.approx(0.1)
        assert descriptor.subtype == audio_stego.SUPPORTED_SUBTYPE

    def test_payload_one_byte_over_capacity_is_refused(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(500))
        report, _ = audio_stego.measure_capacity(cover, 1, 0)
        oversized = bytes(report.max_payload_length + 1)

        with pytest.raises(CapacityError, match="does not fit"):
            audio_stego.embed_audio(
                cover, str(tmp_path / "stego.wav"), oversized, 1, 0
            )

    def test_no_output_file_is_left_after_a_capacity_failure(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(200))
        stego = str(tmp_path / "stego.wav")

        with pytest.raises(CapacityError):
            audio_stego.embed_audio(cover, stego, bytes(10_000), 1, 0)
        assert not os.path.exists(stego)

    def test_start_location_reduces_capacity(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        near, _ = audio_stego.measure_capacity(cover, 1, 0)
        far, _ = audio_stego.measure_capacity(cover, 1, 500)
        assert far.available_capacity_bytes < near.available_capacity_bytes


# --------------------------------------------------------------------------- #
# Errors
# --------------------------------------------------------------------------- #


class TestFileErrors:
    def test_missing_input(self, tmp_path):
        with pytest.raises(FileError, match="not found"):
            audio_stego.embed_audio(
                str(tmp_path / "absent.wav"), str(tmp_path / "out.wav"), PAYLOAD, 1, 0
            )

    def test_input_is_a_directory(self, tmp_path):
        with pytest.raises(FileError, match="directory"):
            audio_stego.embed_audio(
                str(tmp_path), str(tmp_path / "out.wav"), PAYLOAD, 1, 0
            )

    def test_embedding_in_place_is_refused(self, tmp_path):
        """Embedding in place would destroy the cover object."""
        cover = write_audio_file(str(tmp_path), make_audio(4_000))
        with pytest.raises(ValidationError, match="must differ"):
            audio_stego.embed_audio(cover, cover, PAYLOAD, 1, 0)

    def test_the_cover_survives_a_refused_in_place_write(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(4_000))
        before = Path(cover).read_bytes()

        with pytest.raises(ValidationError):
            audio_stego.embed_audio(cover, cover, PAYLOAD, 1, 0)
        assert Path(cover).read_bytes() == before

    def test_occupied_output_is_refused(self, tmp_path):
        """An existing file is never silently overwritten."""
        cover = write_audio_file(str(tmp_path), make_audio(4_000))
        stego = tmp_path / "stego.wav"
        stego.write_bytes(b"existing content")

        with pytest.raises(FileError, match="already occupied"):
            audio_stego.embed_audio(cover, str(stego), PAYLOAD, 1, 0)
        assert stego.read_bytes() == b"existing content"

    def test_overwrite_allows_replacement(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(4_000))
        stego = tmp_path / "stego.wav"
        stego.write_bytes(b"existing content")

        audio_stego.embed_audio(cover, str(stego), PAYLOAD, 1, 0, overwrite=True)
        assert audio_stego.extract_audio(str(stego), 1, 0) == PAYLOAD

    def test_missing_output_directory(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        with pytest.raises(FileError, match="output directory"):
            audio_stego.embed_audio(
                cover, str(tmp_path / "absent" / "out.wav"), PAYLOAD, 1, 0
            )

    def test_no_temporary_files_remain_after_a_successful_embed(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        audio_stego.embed_audio(cover, str(tmp_path / "stego.wav"), PAYLOAD, 1, 0)

        names = sorted(entry.name for entry in tmp_path.iterdir())
        assert names == ["cover.wav", "stego.wav"]


class TestDecodeErrors:
    def test_non_audio_content(self, tmp_path):
        path = write_cover(str(tmp_path), make_cover(8, 8, 3), image_io.PNG, "actually")
        with pytest.raises(DecodeError):
            audio_stego.embed_audio(path, str(tmp_path / "out.wav"), PAYLOAD, 1, 0)

    def test_float_wav_is_refused_with_a_clear_reason(self, tmp_path):
        path = str(tmp_path / "float.wav")
        sf.write(path, np.zeros(1_000, dtype=np.float32), AUDIO_SAMPLE_RATE, subtype="FLOAT")

        with pytest.raises(DecodeError, match="16-bit PCM"):
            audio_stego.measure_capacity(path, 1)

    def test_eight_bit_wav_is_refused(self, tmp_path):
        path = str(tmp_path / "pcm8.wav")
        sf.write(path, np.zeros(1_000, dtype=np.int16), AUDIO_SAMPLE_RATE, subtype="PCM_U8")

        with pytest.raises(DecodeError, match="PCM_16"):
            audio_stego.measure_capacity(path, 1)

    def test_error_messages_omit_the_directory(self, tmp_path):
        path = str(tmp_path / "audio_marker.wav")
        sf.write(path, np.zeros(100, dtype=np.float32), AUDIO_SAMPLE_RATE, subtype="FLOAT")

        with pytest.raises(DecodeError) as caught:
            audio_stego.measure_capacity(path, 1)

        assert "audio_marker.wav" in str(caught.value)
        assert str(tmp_path) not in str(caught.value)


class TestValidationErrors:
    @pytest.mark.parametrize("depth", [0, 9, -1, 100])
    def test_depth_out_of_range(self, tmp_path, depth):
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        with pytest.raises(ValidationError, match="lsb_count"):
            audio_stego.embed_audio(
                cover, str(tmp_path / "out.wav"), PAYLOAD, depth, 0
            )

    def test_boolean_depth(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        with pytest.raises(ValidationError, match="lsb_count"):
            audio_stego.embed_audio(cover, str(tmp_path / "out.wav"), PAYLOAD, True, 0)

    def test_negative_start_location(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        with pytest.raises(ValidationError, match="start_location"):
            audio_stego.embed_audio(cover, str(tmp_path / "out.wav"), PAYLOAD, 1, -1)

    def test_start_location_at_the_sample_count(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        with pytest.raises(ValidationError, match="start_location"):
            audio_stego.embed_audio(cover, str(tmp_path / "out.wav"), PAYLOAD, 1, 1_000)

    def test_boolean_start_location(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        with pytest.raises(ValidationError, match="start_location"):
            audio_stego.embed_audio(cover, str(tmp_path / "out.wav"), PAYLOAD, 1, True)

    def test_non_bytes_payload(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(1_000))
        with pytest.raises(ValidationError, match="payload"):
            audio_stego.embed_audio(
                cover, str(tmp_path / "out.wav"), "a string", 1, 0
            )


class TestExtractionErrors:
    def test_wrong_depth_does_not_raise_a_bare_exception(self, tmp_path):
        """Whatever happens, it must be a StegoError, not an IndexError."""
        cover = write_audio_file(str(tmp_path), make_audio(4_000))
        stego = str(tmp_path / "stego.wav")
        audio_stego.embed_audio(cover, stego, PAYLOAD, 1, 0)

        try:
            recovered = audio_stego.extract_audio(stego, 8, 0)
        except StegoError:
            pass
        else:
            # A mismatched read may decode a plausible length and return wrong
            # bytes with no error at all. That is expected and documented; what
            # matters is that it never silently equals the real payload.
            assert recovered != PAYLOAD

    def test_truncated_stream_is_reported(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(40))
        with pytest.raises(ExtractionError, match="truncated"):
            audio_stego.extract_audio(cover, 1, 35)

    def test_manifest_length_disagreement_is_reported(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(4_000))
        stego = str(tmp_path / "stego.wav")
        audio_stego.embed_audio(cover, stego, PAYLOAD, 2, 0)

        with pytest.raises(ExtractionError, match="disagrees with the manifest"):
            audio_stego.extract_audio(stego, 2, 0, manifest_payload_length=999)

    def test_matching_manifest_length_is_accepted(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(4_000))
        stego = str(tmp_path / "stego.wav")
        audio_stego.embed_audio(cover, stego, PAYLOAD, 2, 0)

        assert (
            audio_stego.extract_audio(
                stego, 2, 0, manifest_payload_length=len(PAYLOAD)
            )
            == PAYLOAD
        )

    def test_extraction_messages_do_not_claim_a_cause(self, tmp_path):
        cover = write_audio_file(str(tmp_path), make_audio(40))
        with pytest.raises(ExtractionError) as caught:
            audio_stego.extract_audio(cover, 1, 35)

        message = str(caught.value).lower()
        for claim in ("wrong passcode", "wrong secret", "wrong start location"):
            assert claim not in message

    def test_missing_input_for_extraction(self, tmp_path):
        with pytest.raises(FileError, match="not found"):
            audio_stego.extract_audio(str(tmp_path / "absent.wav"), 1, 0)


# --------------------------------------------------------------------------- #
# Removed interface
# --------------------------------------------------------------------------- #


class TestRemovedInterface:
    """The superseded names and behaviours must not come back.

    Each was a concrete interoperability problem; see the module docstring of
    ``app/stego/audio_stego.py``.
    """

    def test_old_embed_name_is_gone(self):
        assert not hasattr(audio_stego, "embed_audio_lsb")

    def test_old_extract_name_is_gone(self):
        assert not hasattr(audio_stego, "extract_audio_lsb")

    def test_the_private_magic_marker_is_gone(self):
        assert not hasattr(audio_stego, "MAGIC")

    def test_the_passcode_parameter_is_gone(self):
        """Key-derived behaviour belongs in the cryptography layer."""
        import inspect

        assert "passcode" not in inspect.signature(audio_stego.embed_audio).parameters
        assert "passcode" not in inspect.signature(audio_stego.extract_audio).parameters

    def test_the_layer_imports_nothing_from_the_crypto_package(self):
        """Checked against the parsed imports, not the raw text.

        The module docstring mentions ``app.crypto.envelope`` when explaining
        where the payload marker moved to, so a substring search over the source
        would match prose rather than an import.
        """
        import ast
        import inspect

        tree = ast.parse(inspect.getsource(audio_stego))
        imported: list[str] = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                imported.extend(alias.name for alias in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                imported.append(node.module)

        assert not [name for name in imported if name.startswith("app.crypto")]

    def test_the_shared_bit_helpers_are_actually_used(self):
        import inspect

        source = inspect.getsource(audio_stego)
        assert "from app.stego.bit_utils import" in source

    def test_no_private_bit_conversion_helpers_remain(self):
        """These duplicated bit_utils with different error types."""
        assert not hasattr(audio_stego, "bytes_to_bits") or (
            audio_stego.bytes_to_bits is bit_utils.bytes_to_bits
        )
        assert not hasattr(audio_stego, "build_packet")
        assert not hasattr(audio_stego, "parse_packet")
        assert not hasattr(audio_stego, "_iter_lsb_bits")


# --------------------------------------------------------------------------- #
# Cross-media parity
# --------------------------------------------------------------------------- #


class TestCrossMediaParity:
    """Both media must behave identically wherever they can.

    This is the class that would have caught the original divergence, and the one
    the media facade in ``app/stego/media.py`` relies on.
    """

    def test_the_agreed_positional_signature_works_for_both(self, tmp_path):
        image_cover = write_cover(
            str(tmp_path), make_cover(64, 64, 3), image_io.PNG, "cover"
        )
        audio_cover = write_audio_file(str(tmp_path), make_audio(8_000))

        image_stego.embed_image(
            image_cover, str(tmp_path / "s.png"), PAYLOAD, 3, 100
        )
        audio_stego.embed_audio(
            audio_cover, str(tmp_path / "s.wav"), PAYLOAD, 3, 100
        )

        assert image_stego.extract_image(str(tmp_path / "s.png"), 3, 100) == PAYLOAD
        assert audio_stego.extract_audio(str(tmp_path / "s.wav"), 3, 100) == PAYLOAD

    def test_the_shared_stream_has_a_32_bit_length_header(self):
        from app.stego import lsb_core

        assert lsb_core.LENGTH_HEADER_BITS == 32

    def test_both_layers_report_a_capacity_report(self, tmp_path):
        image_cover = write_cover(
            str(tmp_path), make_cover(32, 32, 3), image_io.PNG, "cover"
        )
        audio_cover = write_audio_file(str(tmp_path), make_audio(8_000))

        image_report, _ = image_stego.measure_capacity(image_cover, 4)
        audio_report, _ = audio_stego.measure_capacity(audio_cover, 4)

        assert isinstance(image_report, capacity.CapacityReport)
        assert isinstance(audio_report, capacity.CapacityReport)

    def test_one_handler_catches_errors_from_both_layers(self, tmp_path):
        """The old audio layer raised bare ValueError, which this would miss."""
        image_cover = write_cover(
            str(tmp_path), make_cover(8, 8, 3), image_io.PNG, "cover"
        )
        audio_cover = write_audio_file(str(tmp_path), make_audio(1_000))

        for call in (
            lambda: image_stego.embed_image(
                image_cover, str(tmp_path / "a.png"), PAYLOAD, 99, 0
            ),
            lambda: audio_stego.embed_audio(
                audio_cover, str(tmp_path / "a.wav"), PAYLOAD, 99, 0
            ),
        ):
            with pytest.raises(StegoError):
                call()

    @pytest.mark.parametrize("depth", range(1, 9))
    def test_identical_payloads_produce_identical_low_bits(self, tmp_path, depth):
        """The two media must agree on bit ordering, not merely round-trip."""
        payload = bytes(range(40))
        encoded = len(payload).to_bytes(4, "big") + payload
        expected = bit_utils.pack_bits_to_groups(
            bit_utils.bytes_to_bits(encoded), depth
        )

        image_cover = write_cover(
            str(tmp_path), make_cover(64, 64, 3), image_io.PNG, f"c{depth}"
        )
        audio_cover = write_audio_file(
            str(tmp_path), make_audio(8_000), f"a{depth}"
        )
        image_out = str(tmp_path / f"s{depth}.png")
        audio_out = str(tmp_path / f"s{depth}.wav")

        image_stego.embed_image(image_cover, image_out, payload, depth, 0)
        audio_stego.embed_audio(audio_cover, audio_out, payload, depth, 0)

        image_array, _ = image_io.load_image(image_out)
        image_flat, _ = image_stego.embeddable_stream(image_array)
        image_bits = bit_utils.read_low_bits(
            image_flat[: expected.size], depth, 8
        )

        audio_samples, _ = audio_stego.read_audio(audio_out)
        audio_flat, _ = audio_stego.embeddable_stream(audio_samples)
        audio_bits = bit_utils.read_low_bits(
            audio_flat[: expected.size], depth, 16
        )

        assert np.array_equal(image_bits.astype(np.uint16), expected)
        assert np.array_equal(audio_bits.astype(np.uint16), expected)

    def test_both_layers_expose_the_same_result_fields(self, tmp_path):
        image_cover = write_cover(
            str(tmp_path), make_cover(64, 64, 3), image_io.PNG, "cover"
        )
        audio_cover = write_audio_file(str(tmp_path), make_audio(8_000))

        image_result = image_stego.embed_image(
            image_cover, str(tmp_path / "s.png"), PAYLOAD, 3, 10
        )
        audio_result = audio_stego.embed_audio(
            audio_cover, str(tmp_path / "s.wav"), PAYLOAD, 3, 10
        )

        shared = {
            "output_path",
            "container_format",
            "descriptor",
            "capacity",
            "lsb_count",
            "start_location",
            "payload_length",
            "encoded_length",
            "samples_written",
        }
        assert shared <= set(vars(image_result))
        assert shared <= set(vars(audio_result))
        assert image_result.encoded_length == audio_result.encoded_length
        assert image_result.samples_written == audio_result.samples_written
