"""The file-size preservation experiment, and the evidence it produces.

The project plan asks for this to be investigated and the outcome recorded, and
warns specifically against claiming exact preservation works in general unless
testing shows it. So this file is written to *find out*, and its assertions are
about the mechanism rather than about a hoped-for answer:

* WAV and BMP are asserted to preserve size exactly, because that follows from how
  they store samples and a failure would be a bug in the writer.
* PNG is **not** asserted to be matchable. What is asserted is that when the
  experiment reports a match the file really is byte-for-byte the right length and
  still decodes to the same pixels, and that when it reports a failure it explains
  why. Both outcomes are exercised deliberately.
* Video is asserted only to be reported as not applicable, since a protected clip is
  a full re-encode.

The results are written to ``evidence/results/size_preservation.{json,md}`` so the
submission has the record the plan asks for.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import pytest

from app.analysis import size_preservation
from app.analysis.size_preservation import (
    DEFLATE_LEVELS,
    MIN_PNG_CHUNK_OVERHEAD,
    PADDING_CHUNK_TYPE,
    SizeResult,
)
from app.stego import audio_stego, image_io, image_stego, media, video_stego
from app.stego.errors import ValidationError
from app.utils import constants, file_utils
from conftest import (
    make_audio,
    make_cover,
    make_video_frames,
    write_audio_file,
    write_cover,
    write_video_file,
)

PAYLOAD = b"A payload whose presence must not have to change the file's length." * 3

_RESULTS: list[dict[str, Any]] = []


def record(result: SizeResult, scenario: str) -> None:
    row = result.as_dict()
    row["scenario"] = scenario
    _RESULTS.append(row)


@pytest.fixture(scope="module", autouse=True)
def write_evidence():
    """Write the experiment's artefacts once every case in this file has run."""
    _RESULTS.clear()
    yield

    if not _RESULTS:  # pragma: no cover - only when the module is deselected
        return

    directory = Path(__file__).resolve().parents[1] / "evidence" / "results"
    directory.mkdir(parents=True, exist_ok=True)

    applicable = [row for row in _RESULTS if row["applicable"]]
    matched = [row for row in applicable if row["exact"]]
    attempted = [row for row in _RESULTS if row["attempted"]]
    attempted_and_matched = [row for row in attempted if row["exact"]]

    file_utils.write_json_atomic(
        str(directory / "size_preservation.json"),
        {
            "experiment": "exact file-size preservation",
            "total": len(_RESULTS),
            "applicable": len(applicable),
            "exact": len(matched),
            "attempts": len(attempted),
            "attempts_that_matched": len(attempted_and_matched),
            "cases": _RESULTS,
        },
        overwrite=True,
    )

    lines = [
        "# File-Size Preservation Experiment",
        "",
        "Generated by `tests/test_size_preservation.py`. Every row is one measured "
        "case, not a claim.",
        "",
        "## What was asked",
        "",
        "Investigate whether a stego file can be made exactly the same size as its "
        "cover, and record when it succeeds and when it does not. The plan is "
        "explicit that this must not be claimed in general unless testing proves it, "
        "so the failures below are part of the result rather than omissions from it.",
        "",
        "## Answer, by container",
        "",
        "| Container | Exact size? | Why |",
        "|---|---|---|",
        "| WAV (PCM 16) | always | Samples are stored literally at fixed width, so "
        "replacing low bits changes values and not counts. |",
        "| BMP | always | Same reason: uncompressed, fixed-stride pixel storage. |",
        "| PNG | depends on the image | The pixel data is DEFLATE-compressed, so the "
        "answer is a property of the individual image rather than of the format. Three "
        "outcomes were measured; see below. |",
        "| MKV (FFV1) | not applicable | A protected clip is re-encoded from decoded "
        "frames, so its size reflects the codec, not the payload. |",
        "",
        "### The three PNG outcomes, measured",
        "",
        "1. **Free.** A cover that is already incompressible (photographic noise) is "
        "stored rather than compressed, so every DEFLATE level produces the same "
        "length and the stego file comes out at the cover's size with nothing done. "
        "This is the best case and needs no padding chunk, so it leaves no trace.",
        "2. **Matched by padding.** When the best of the ten candidate encodings lands "
        "*under* the cover's length, the shortfall is closed exactly with an ancillary "
        "chunk. Observed for a two-value cover at depth 8, where replacing whole low "
        "bytes made the pixel data more compressible than the cover's.",
        "3. **Impossible.** When every candidate is already *larger* than the cover — "
        "the usual case for a smooth or flat image, because LSB replacement pushes low "
        "bits toward random and random data does not compress — the size cannot be "
        "matched at all. Bytes cannot be removed from a PNG without changing its "
        "pixels.",
        "",
        "## Measured cases",
        "",
        f"- cases measured: {len(_RESULTS)}",
        f"- cases where the question applies: {len(applicable)}",
        f"- of those, exactly the cover's size: {len(matched)}",
        f"- PNG matching attempts: {len(attempted)}, of which "
        f"{len(attempted_and_matched)} succeeded",
        "",
        "| Scenario | Container | Cover | Stego | Final | Difference | Exact | "
        "Strategy |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in _RESULTS:
        if not row["applicable"]:
            exact = "n/a"
        else:
            exact = "yes" if row["exact"] else "no"
        lines.append(
            f"| {row['scenario']} | {row['container']} | {row['cover_size']:,} | "
            f"{row['stego_size']:,} | {row['final_size']:,} | "
            f"{row['difference']:+,} | {exact} | {row['strategy']} |"
        )

    lines += [
        "",
        "## The PNG strategy in full",
        "",
        "1. Re-encode the stego pixels at every DEFLATE level from 0 to 9. The levels "
        "produce different lengths, so one may already equal the cover's. No pixel "
        "changes.",
        "2. If the smallest candidate is still short of the target, insert an "
        f"ancillary `{PADDING_CHUNK_TYPE.decode()}` chunk sized to close the gap "
        "exactly. Ancillary chunks are skippable by specification, so the pixels "
        "still decode identically.",
        "",
        "### Where it stops working",
        "",
        f"- If every candidate is already **larger** than the cover, the size cannot "
        f"be matched. Bytes cannot be removed from a PNG without changing its "
        f"pixels. This is the usual case at higher LSB depths, and it is the reason "
        f"exact PNG preservation is reported per file rather than promised.",
        f"- If the shortfall is smaller than {MIN_PNG_CHUNK_OVERHEAD} bytes, it cannot "
        f"be padded either: that is what a PNG chunk costs with an empty payload.",
        "",
        "### A cost worth naming",
        "",
        "A padding chunk is an unusual feature in an otherwise plain PNG. A file "
        "padded to match its cover's size may therefore be *more* conspicuous to an "
        "analyst than one that is simply the wrong size. Matching the size is not "
        "automatically the better choice.",
        "",
    ]
    file_utils.write_text_atomic(
        str(directory / "size_preservation.md"), "\n".join(lines), overwrite=True
    )


# --------------------------------------------------------------------------- #
# Fixtures
# --------------------------------------------------------------------------- #


@pytest.fixture()
def png_cover(tmp_path):
    return write_cover(str(tmp_path), make_cover(96, 96, 3), image_io.PNG, "cover")


@pytest.fixture()
def flat_png_cover(tmp_path):
    """A flat cover, chosen because it compresses to almost nothing.

    That makes the stego version *grow* dramatically, which is the case where PNG
    size preservation is impossible. Used to exercise the failure branch honestly
    rather than only the branch that works.
    """
    return write_cover(
        str(tmp_path), make_cover(96, 96, 3, "flat"), image_io.PNG, "flat"
    )


@pytest.fixture()
def noisy_png_cover(tmp_path):
    """Pure noise: already incompressible, so DEFLATE stores it and the size is fixed.

    The measured consequence is that every level produces the *same* length, and the
    stego file therefore comes out at the cover's size with nothing done at all. Worth
    a fixture of its own because it is the one PNG case that is free.
    """
    return write_cover(
        str(tmp_path), make_cover(96, 96, 3, "noise"), image_io.PNG, "noisy"
    )


@pytest.fixture()
def extremes_png_cover(tmp_path):
    """Only 0 and 255, so it compresses somewhat but not to nothing.

    Measured to be the case where the strategy genuinely works: the best of the ten
    levels comes out a few dozen bytes *under* the cover, which padding can close
    exactly. Chosen empirically rather than hoped for.
    """
    return write_cover(
        str(tmp_path), make_cover(96, 96, 3, "extremes"), image_io.PNG, "extremes"
    )


@pytest.fixture()
def bmp_cover(tmp_path):
    return write_cover(str(tmp_path), make_cover(96, 96, 3), image_io.BMP, "cover_bmp")


@pytest.fixture()
def wav_cover(tmp_path):
    return write_audio_file(str(tmp_path), make_audio(40_000))


@pytest.fixture()
def mkv_cover(tmp_path):
    return write_video_file(
        str(tmp_path), make_video_frames(frame_count=6, height=32, width=48), "clip"
    )


# --------------------------------------------------------------------------- #
# The containers where it is free
# --------------------------------------------------------------------------- #


class TestInherentPreservation:
    def test_wav_preserves_size_exactly(self, wav_cover, tmp_path):
        stego = str(tmp_path / "stego.wav")
        audio_stego.embed_audio(wav_cover, stego, PAYLOAD, 2, 0)

        result = size_preservation.size_outcome(wav_cover, stego)
        record(result, "WAV, depth 2")

        assert result.exact is True
        assert result.inherent is True
        assert result.difference == 0

    @pytest.mark.parametrize("depth", [1, 4, 8])
    def test_wav_preserves_size_at_every_depth(self, wav_cover, tmp_path, depth):
        """Depth cannot matter here, and asserting that is the point."""
        stego = str(tmp_path / f"stego{depth}.wav")
        audio_stego.embed_audio(wav_cover, stego, PAYLOAD, depth, 0)

        assert os.path.getsize(stego) == os.path.getsize(wav_cover)

    def test_bmp_preserves_size_exactly(self, bmp_cover, tmp_path):
        stego = str(tmp_path / "stego.bmp")
        image_stego.embed_image(bmp_cover, stego, PAYLOAD, 3, 0)

        result = size_preservation.size_outcome(bmp_cover, stego)
        record(result, "BMP, depth 3")

        assert result.exact is True
        assert result.inherent is True

    @pytest.mark.parametrize("depth", [1, 4, 8])
    def test_bmp_preserves_size_at_every_depth(self, bmp_cover, tmp_path, depth):
        stego = str(tmp_path / f"stego{depth}.bmp")
        image_stego.embed_image(bmp_cover, stego, PAYLOAD, depth, 0)

        assert os.path.getsize(stego) == os.path.getsize(bmp_cover)

    def test_the_reason_is_recorded_not_just_the_result(self, wav_cover, tmp_path):
        stego = str(tmp_path / "stego.wav")
        audio_stego.embed_audio(wav_cover, stego, PAYLOAD, 2, 0)

        result = size_preservation.size_outcome(wav_cover, stego)
        assert any("byte counts" in note for note in result.notes)


# --------------------------------------------------------------------------- #
# PNG: the interesting case
# --------------------------------------------------------------------------- #


class TestPngBaseline:
    def test_embedding_usually_grows_a_compressible_png(
        self, flat_png_cover, tmp_path
    ):
        """The mechanism, stated as a test: random low bits do not compress."""
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(flat_png_cover, stego, PAYLOAD, 8, 0)

        result = size_preservation.size_outcome(flat_png_cover, stego)
        record(result, "PNG (flat cover), depth 8, baseline")

        assert result.exact is False
        assert result.difference > 0
        assert result.inherent is False

    def test_the_baseline_explains_why_png_differs(self, png_cover, tmp_path):
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(png_cover, stego, PAYLOAD, 2, 0)

        result = size_preservation.size_outcome(png_cover, stego)
        assert any("DEFLATE" in note for note in result.notes)


class TestDeflateLevels:
    def test_every_level_encodes_the_same_pixels(self, png_cover, tmp_path):
        """The size varies; the pixels must not."""
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(png_cover, stego, PAYLOAD, 2, 0)
        array, _ = image_io.load_image(stego)

        import io

        from PIL import Image

        for level in DEFLATE_LEVELS:
            data = size_preservation.encode_png_at_level(array, level)
            decoded = Image.open(io.BytesIO(data))
            assert (
                __import__("numpy").asarray(decoded).reshape(array.shape) == array
            ).all(), level

    def test_the_levels_produce_a_range_of_sizes_for_compressible_content(
        self, flat_png_cover, tmp_path
    ):
        """Otherwise step 1 of the strategy would be pointless."""
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(flat_png_cover, stego, PAYLOAD, 2, 0)
        array, _ = image_io.load_image(stego)

        sizes = {
            len(size_preservation.encode_png_at_level(array, level))
            for level in DEFLATE_LEVELS
        }
        assert len(sizes) > 1

    def test_the_levels_all_agree_for_incompressible_content(
        self, noisy_png_cover, tmp_path
    ):
        """A measured limit of step 1, not a bug.

        Noise cannot be compressed, so zlib emits stored blocks at every level and all
        ten candidates come out the same length. For such a file the level sweep offers
        no choice at all — and does not need to, because the stego file is already the
        cover's size for the same reason.
        """
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(noisy_png_cover, stego, PAYLOAD, 2, 0)
        array, _ = image_io.load_image(stego)

        sizes = {
            len(size_preservation.encode_png_at_level(array, level))
            for level in DEFLATE_LEVELS
        }
        assert len(sizes) == 1
        assert os.path.getsize(stego) == os.path.getsize(noisy_png_cover)

    def test_an_invalid_level_is_refused(self, png_cover):
        array, _ = image_io.load_image(png_cover)
        with pytest.raises(ValidationError, match="DEFLATE level"):
            size_preservation.encode_png_at_level(array, 11)


class TestPadding:
    def test_padding_reaches_the_target_exactly(self, png_cover):
        raw = Path(png_cover).read_bytes()
        target = len(raw) + 100

        padded = size_preservation.pad_png_to_size(raw, target)
        assert len(padded) == target

    def test_padding_leaves_the_pixels_identical(self, png_cover, tmp_path):
        raw = Path(png_cover).read_bytes()
        padded = size_preservation.pad_png_to_size(raw, len(raw) + 500)

        target = tmp_path / "padded.png"
        target.write_bytes(padded)

        before, _ = image_io.load_image(png_cover)
        after, _ = image_io.load_image(str(target))
        assert (before == after).all()

    def test_the_padding_chunk_is_ancillary_and_private(self):
        """Both letters matter: ancillary means skippable, private means no clash."""
        assert PADDING_CHUNK_TYPE[0:1].islower()  # ancillary
        assert PADDING_CHUNK_TYPE[1:2].islower()  # private

    def test_padding_to_the_same_size_is_a_no_op(self, png_cover):
        raw = Path(png_cover).read_bytes()
        assert size_preservation.pad_png_to_size(raw, len(raw)) == raw

    def test_shrinking_is_refused_with_a_reason(self, png_cover):
        raw = Path(png_cover).read_bytes()
        with pytest.raises(ValidationError, match="cannot be shortened"):
            size_preservation.pad_png_to_size(raw, len(raw) - 100)

    def test_a_gap_smaller_than_a_chunk_is_refused(self, png_cover):
        raw = Path(png_cover).read_bytes()
        with pytest.raises(ValidationError, match="chunk costs"):
            size_preservation.pad_png_to_size(raw, len(raw) + 5)

    def test_a_non_png_is_refused(self):
        with pytest.raises(Exception):
            size_preservation.pad_png_to_size(b"not a png at all", 500)


class TestPngPreservationAttempt:
    #: The one combination measured to reach the padding branch: a two-value cover at
    #: depth 8. Replacing whole low bytes with payload bytes makes the pixel data
    #: *more* compressible than the cover's, so the best candidate lands under the
    #: target and the shortfall can be closed. Found by sweeping the patterns and
    #: depths, not assumed.
    PADDING_CASE_DEPTH = 8

    def test_the_strategy_matches_by_padding_where_measurement_says_it_can(
        self, extremes_png_cover, tmp_path
    ):
        """The success case, on the one combination measured to produce it.

        Not a general claim. What is asserted is that *when* the strategy reports a
        match, the file really is the cover's length to the byte and really does decode
        to the same pixels — the part that must never be wrong.
        """
        depth = self.PADDING_CASE_DEPTH
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(extremes_png_cover, stego, PAYLOAD, depth, 0)
        output = str(tmp_path / "matched.png")

        result = size_preservation.preserve_png_size(
            extremes_png_cover, stego, output
        )

        assert result.attempted is True
        assert result.exact is True
        assert os.path.getsize(output) == os.path.getsize(extremes_png_cover)
        assert result.content_unchanged is True
        assert result.details["padded_bytes"] > 0

    def test_the_matched_file_is_still_a_readable_png(
        self, extremes_png_cover, tmp_path
    ):
        """A padded file the application could not read back would be useless."""
        depth = self.PADDING_CASE_DEPTH
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(extremes_png_cover, stego, PAYLOAD, depth, 0)
        output = str(tmp_path / "matched.png")
        size_preservation.preserve_png_size(extremes_png_cover, stego, output)

        before, _ = image_io.load_image(stego)
        after, _ = image_io.load_image(output)
        assert (before == after).all()

    def test_the_payload_still_extracts_from_the_matched_file(
        self, extremes_png_cover, tmp_path
    ):
        """The whole point: matching the size must not cost the payload."""
        depth = self.PADDING_CASE_DEPTH
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(extremes_png_cover, stego, PAYLOAD, depth, 0)
        output = str(tmp_path / "matched.png")
        size_preservation.preserve_png_size(extremes_png_cover, stego, output)

        assert image_stego.extract_image(output, depth, 0) == PAYLOAD

    def test_a_level_sweep_alone_can_match_an_incompressible_cover(
        self, noisy_png_cover, tmp_path
    ):
        """Step 1 on its own, with no padding involved.

        A noise cover is stored rather than compressed, so one of the ten candidates
        equals the cover's length exactly and nothing has to be appended. This is the
        cleanest outcome available: exact size, no unusual chunk, no trace.
        """
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(noisy_png_cover, stego, PAYLOAD, 8, 0)

        result = size_preservation.preserve_png_size(
            noisy_png_cover, stego, str(tmp_path / "matched.png")
        )
        record(result, "PNG (noise cover), depth 8, attempt")

        assert result.exact is True
        assert result.details["padded_bytes"] == 0
        assert result.details["exact_level"] is not None
        assert "re-encoding at DEFLATE level" in result.strategy

    def test_a_noise_cover_needs_no_help_at_all(self, noisy_png_cover, tmp_path):
        """Free preservation, recorded because it is the cheapest outcome available."""
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(noisy_png_cover, stego, PAYLOAD, 2, 0)

        baseline = size_preservation.size_outcome(noisy_png_cover, stego)
        record(baseline, "PNG (noise cover), depth 2, baseline")

        assert baseline.exact is True
        assert baseline.attempted is False

    def test_an_impossible_case_is_reported_rather_than_forced(
        self, flat_png_cover, tmp_path
    ):
        """A flat cover compresses to nothing, so the stego version cannot shrink to it."""
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(flat_png_cover, stego, PAYLOAD, 8, 0)

        result = size_preservation.preserve_png_size(
            flat_png_cover, stego, str(tmp_path / "attempted.png")
        )
        record(result, "PNG (flat cover), depth 8, attempt")

        assert result.exact is False
        assert "not matched" in result.strategy
        assert any("cannot be removed" in note for note in result.notes)
        # And the pixels still survived the attempt.
        assert result.content_unchanged is True

    def test_the_attempt_records_every_level_it_tried(self, png_cover, tmp_path):
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(png_cover, stego, PAYLOAD, 2, 0)

        result = size_preservation.preserve_png_size(
            png_cover, stego, str(tmp_path / "out.png")
        )
        assert set(result.details["sizes_by_deflate_level"]) == set(DEFLATE_LEVELS)

    def test_padding_is_disclosed_when_it_was_used(
        self, extremes_png_cover, tmp_path
    ):
        """Silently padding a file to look right would be the dishonest option."""
        stego = str(tmp_path / "stego.png")
        image_stego.embed_image(
            extremes_png_cover, stego, PAYLOAD, self.PADDING_CASE_DEPTH, 0
        )

        result = size_preservation.preserve_png_size(
            extremes_png_cover, stego, str(tmp_path / "out.png")
        )
        assert result.details["padded_bytes"] > 0
        assert any("conspicuous" in note for note in result.notes)
        assert "padding chunk" in result.strategy

    def test_a_bmp_is_refused_by_the_png_experiment(self, bmp_cover, tmp_path):
        stego = str(tmp_path / "stego.bmp")
        image_stego.embed_image(bmp_cover, stego, PAYLOAD, 2, 0)

        with pytest.raises(ValidationError, match="applies to PNG"):
            size_preservation.preserve_png_size(
                bmp_cover, stego, str(tmp_path / "out.bmp")
            )

    @pytest.mark.parametrize("depth", [1, 2, 4, 8])
    def test_the_outcome_is_recorded_across_depths(
        self, extremes_png_cover, tmp_path, depth
    ):
        """The sweep the evidence table reports.

        No particular outcome is asserted, because the answer legitimately depends on
        the depth: more bits replaced means less compressible pixel data, so a match
        that is available at depth 1 may not be at depth 8. What is asserted is that
        every outcome is lossless and explains itself.
        """
        stego = str(tmp_path / f"stego{depth}.png")
        image_stego.embed_image(extremes_png_cover, stego, PAYLOAD, depth, 0)

        result = size_preservation.preserve_png_size(
            extremes_png_cover, stego, str(tmp_path / f"out{depth}.png")
        )
        record(result, f"PNG (two-value cover), depth {depth}, attempt")

        assert result.content_unchanged is True
        assert result.notes


# --------------------------------------------------------------------------- #
# Wired into the protect workflow
# --------------------------------------------------------------------------- #


class TestThroughProtect:
    """The option as a user meets it, including the part that could go wrong.

    Rewriting the stego file after embedding is only safe if the manifest is written
    afterwards, because the manifest records the file's digest. That ordering is the
    thing most worth a test here: getting it wrong would produce a manifest describing
    a file that no longer exists, and the symptom would appear much later.
    """

    @pytest.fixture(scope="class")
    def keys(self):
        from app.crypto import key_manager

        return key_manager.generate_key_pair(constants.RSA_MIN_KEY_SIZE)

    def _protect(self, cover, tmp_path, keys, *, match, depth=2, name="stego"):
        from app.crypto import key_manager
        from app.crypto.encryption import MIN_SCRYPT_N
        from app.verification.protect import protect_media

        private_key, public_key = keys
        public_path = str(tmp_path / "public.pem")
        key_manager.save_public_key(public_key, public_path, overwrite=True)

        extension = os.path.splitext(cover)[1]
        result = protect_media(
            cover,
            str(tmp_path / f"{name}{extension}"),
            b"A short protected message.",
            private_key,
            media_id="SIZE-001",
            lsb_depth=depth,
            start_secret="the start secret",
            match_cover_size=match,
            scrypt_n=MIN_SCRYPT_N,
            scrypt_r=8,
            scrypt_p=1,
        )
        return result, public_path

    def test_the_option_is_off_by_default(self, png_cover, tmp_path, keys):
        result, _ = self._protect(png_cover, tmp_path, keys, match=False)
        assert result.size_preservation is None

    def test_the_outcome_is_reported_when_the_option_is_on(
        self, png_cover, tmp_path, keys
    ):
        result, _ = self._protect(png_cover, tmp_path, keys, match=True)

        assert result.size_preservation is not None
        assert result.size_preservation.notes

    def test_the_manifest_digest_matches_the_rewritten_file(
        self, noisy_png_cover, tmp_path, keys
    ):
        """The ordering test. A stale digest here would be a real bug.

        The noise cover is used because it reliably *does* get rewritten and matched,
        so the digest genuinely has to have been taken afterwards for this to pass.
        """
        result, _ = self._protect(noisy_png_cover, tmp_path, keys, match=True, depth=8)

        assert result.size_preservation.exact is True
        assert result.manifest.stego_sha256 == file_utils.file_sha256(
            result.stego_path
        )

    def test_the_rewritten_file_still_verifies(
        self, noisy_png_cover, tmp_path, keys
    ):
        """Matching the size must not cost the verdict."""
        from app.verification import verdicts
        from app.verification.verifier import verify_media

        result, public_path = self._protect(
            noisy_png_cover, tmp_path, keys, match=True, depth=8
        )
        assert result.size_preservation.exact is True
        assert os.path.getsize(result.stego_path) == os.path.getsize(noisy_png_cover)

        outcome = verify_media(
            result.stego_path,
            result.manifest_path,
            public_path,
            start_secret="the start secret",
        )
        assert outcome.verdict == verdicts.VERDICT_AUTHENTIC

    def test_a_failure_to_match_does_not_stop_the_protect(
        self, flat_png_cover, tmp_path, keys
    ):
        """The size is a nice-to-have; refusing to protect over it would be absurd."""
        from app.verification import verdicts
        from app.verification.verifier import verify_media

        result, public_path = self._protect(
            flat_png_cover, tmp_path, keys, match=True, depth=8
        )
        assert result.size_preservation.exact is False

        outcome = verify_media(
            result.stego_path,
            result.manifest_path,
            public_path,
            start_secret="the start secret",
        )
        assert outcome.verdict == verdicts.VERDICT_AUTHENTIC

    def test_a_wav_cover_reports_that_nothing_was_needed(
        self, wav_cover, tmp_path, keys
    ):
        result, _ = self._protect(wav_cover, tmp_path, keys, match=True)

        assert result.size_preservation.inherent is True
        assert result.size_preservation.exact is True
        assert result.size_preservation.attempted is False

    def test_a_video_cover_reports_that_the_question_does_not_apply(
        self, mkv_cover, tmp_path, keys
    ):
        result, _ = self._protect(mkv_cover, tmp_path, keys, match=True)

        assert result.size_preservation.applicable is False
        assert result.size_preservation.attempted is False


# --------------------------------------------------------------------------- #
# Video
# --------------------------------------------------------------------------- #


class TestVideo:
    def test_video_is_reported_as_not_applicable(self, mkv_cover, tmp_path):
        stego = str(tmp_path / "stego.mkv")
        video_stego.embed_video(mkv_cover, stego, PAYLOAD, 2, 0)

        result = size_preservation.size_outcome(mkv_cover, stego)
        record(result, "MKV (FFV1), depth 2")

        assert result.applicable is False
        assert result.attempted is False
        assert result.inherent is False
        assert "not applicable" in result.strategy
        assert any("re-encoded" in note for note in result.notes)
        assert "does not apply" in result.summary()

    def test_a_coincidental_size_match_is_not_counted_as_preservation(
        self, mkv_cover, tmp_path
    ):
        """Two separate FFV1 encodings can land on the same length by chance.

        Recording that as a success would be the most tempting way to overstate this
        experiment's result, so the coincidence is called out explicitly when it
        happens rather than tallied.
        """
        stego = str(tmp_path / "stego.mkv")
        video_stego.embed_video(mkv_cover, stego, PAYLOAD, 2, 0)

        result = size_preservation.size_outcome(mkv_cover, stego)
        if result.stego_size == result.cover_size:
            assert any("coincidence" in note for note in result.notes)
        assert result.applicable is False
